/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PrintRouteImport } from './routes/print'
import { Route as LifeGroupsRouteImport } from './routes/life-groups'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiscipleshipRouteImport } from './routes/discipleship'
import { Route as IndexRouteImport } from './routes/index'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeGroupsRoute = LifeGroupsRouteImport.update({
  id: '/life-groups',
  path: '/life-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscipleshipRoute = DiscipleshipRouteImport.update({
  id: '/discipleship',
  path: '/discipleship',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discipleship': typeof DiscipleshipRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/life-groups': typeof LifeGroupsRoute
  '/print': typeof PrintRoute
  '/roster': typeof RosterRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discipleship': typeof DiscipleshipRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/life-groups': typeof LifeGroupsRoute
  '/print': typeof PrintRoute
  '/roster': typeof RosterRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discipleship': typeof DiscipleshipRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/life-groups': typeof LifeGroupsRoute
  '/print': typeof PrintRoute
  '/roster': typeof RosterRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discipleship'
    | '/docs'
    | '/health'
    | '/life-groups'
    | '/print'
    | '/roster'
    | '/teams'
    | '/users'
    | '/volunteers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discipleship'
    | '/docs'
    | '/health'
    | '/life-groups'
    | '/print'
    | '/roster'
    | '/teams'
    | '/users'
    | '/volunteers'
  id:
    | '__root__'
    | '/'
    | '/discipleship'
    | '/docs'
    | '/health'
    | '/life-groups'
    | '/print'
    | '/roster'
    | '/teams'
    | '/users'
    | '/volunteers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscipleshipRoute: typeof DiscipleshipRoute
  DocsRoute: typeof DocsRoute
  HealthRoute: typeof HealthRoute
  LifeGroupsRoute: typeof LifeGroupsRoute
  PrintRoute: typeof PrintRoute
  RosterRoute: typeof RosterRoute
  TeamsRoute: typeof TeamsRoute
  UsersRoute: typeof UsersRoute
  VolunteersRoute: typeof VolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-groups': {
      id: '/life-groups'
      path: '/life-groups'
      fullPath: '/life-groups'
      preLoaderRoute: typeof LifeGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipleship': {
      id: '/discipleship'
      path: '/discipleship'
      fullPath: '/discipleship'
      preLoaderRoute: typeof DiscipleshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscipleshipRoute: DiscipleshipRoute,
  DocsRoute: DocsRoute,
  HealthRoute: HealthRoute,
  LifeGroupsRoute: LifeGroupsRoute,
  PrintRoute: PrintRoute,
  RosterRoute: RosterRoute,
  TeamsRoute: TeamsRoute,
  UsersRoute: UsersRoute,
  VolunteersRoute: VolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
